# .releaserc.yaml
branches:
  - master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - assets: []
      failComment: false
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - LICENSE
      message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
