name: Validar PR - Conventional Commits (Terraform)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  validate:
    name: Validar nome do PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar se há arquivos Terraform no PR
        id: check_tf
        run: |
          CHANGED_FILES=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            --jq '.[] | .filename' | grep '\.tf$' || true)
          echo "Arquivos Terraform alterados:"
          echo "$CHANGED_FILES"
          if [ -z "$CHANGED_FILES" ]; then
            echo "terraform_changed=false" >> $GITHUB_OUTPUT
          else
            echo "terraform_changed=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validar título do PR com Conventional Commits
        if: steps.check_tf.outputs.terraform_changed == 'true'
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "Título do PR: $TITLE"

          # Expressão Regular baseada no padrão Conventional Commits
          if echo "$TITLE" | grep -Eq '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci)(\([a-z0-9_-]+\))?!?: .+'; then
            echo "✅ Título segue o padrão Conventional Commits."
          else
            echo "❌ Erro: o título do PR não segue o padrão Conventional Commits."
            echo "Exemplos válidos:"
            echo "  feat(vpc): adiciona suporte multi-az"
            echo "  fix(s3): corrige política pública"
            echo "  chore: atualiza dependências"
            exit 1
          fi
